# TCL File Generated by Component Editor 18.1
# Sun Aug 11 05:29:41 BRT 2019
# DO NOT MODIFY


# 
# accelerator "custom accelerator" v1.0
# Tiago 2019.08.11.05:29:41
# ainda um teste com um contador
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module accelerator
# 
set_module_property DESCRIPTION "ainda um teste com um contador"
set_module_property NAME accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Tiago
set_module_property DISPLAY_NAME "custom accelerator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL custom_acc_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file custom_acc_top.v VERILOG PATH acelerador/custom_acc_top.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter NUM_CICLOS INTEGER 50000000
set_parameter_property NUM_CICLOS DEFAULT_VALUE 50000000
set_parameter_property NUM_CICLOS DISPLAY_NAME NUM_CICLOS
set_parameter_property NUM_CICLOS TYPE INTEGER
set_parameter_property NUM_CICLOS UNITS None
set_parameter_property NUM_CICLOS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 50000000
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point control_in
# 
add_interface control_in conduit end
set_interface_property control_in associatedClock ""
set_interface_property control_in associatedReset ""
set_interface_property control_in ENABLED true
set_interface_property control_in EXPORT_OF ""
set_interface_property control_in PORT_NAME_MAP ""
set_interface_property control_in CMSIS_SVD_VARIABLES ""
set_interface_property control_in SVD_ADDRESS_GROUP ""

add_interface_port control_in i_start export Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst reset reset Input 1


# 
# connection point control_out
# 
add_interface control_out conduit end
set_interface_property control_out associatedClock ""
set_interface_property control_out associatedReset ""
set_interface_property control_out ENABLED true
set_interface_property control_out EXPORT_OF ""
set_interface_property control_out PORT_NAME_MAP ""
set_interface_property control_out CMSIS_SVD_VARIABLES ""
set_interface_property control_out SVD_ADDRESS_GROUP ""

add_interface_port control_out o_finish export Output 1

