# TCL File Generated by Component Editor 18.1
# Sun Aug 18 20:52:01 BRT 2019
# DO NOT MODIFY


# 
# conv_acc "conv acc" v1.0
# Tiago 2019.08.18.20:52:01
# simple FIR filter
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module conv_acc
# 
set_module_property DESCRIPTION "simple FIR filter"
set_module_property NAME conv_acc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Tiago
set_module_property DISPLAY_NAME "conv acc"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL custom_logic_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file custom_logic_top.v VERILOG PATH acelerador/custom_logic_top.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter OFFSET_ENTRADA NATURAL 0 ""
set_parameter_property OFFSET_ENTRADA DEFAULT_VALUE 0
set_parameter_property OFFSET_ENTRADA DISPLAY_NAME OFFSET_ENTRADA
set_parameter_property OFFSET_ENTRADA WIDTH ""
set_parameter_property OFFSET_ENTRADA TYPE NATURAL
set_parameter_property OFFSET_ENTRADA UNITS None
set_parameter_property OFFSET_ENTRADA ALLOWED_RANGES 0:2147483647
set_parameter_property OFFSET_ENTRADA DESCRIPTION ""
set_parameter_property OFFSET_ENTRADA HDL_PARAMETER true
add_parameter OFFSET_SAIDA NATURAL 512 ""
set_parameter_property OFFSET_SAIDA DEFAULT_VALUE 512
set_parameter_property OFFSET_SAIDA DISPLAY_NAME OFFSET_SAIDA
set_parameter_property OFFSET_SAIDA WIDTH ""
set_parameter_property OFFSET_SAIDA TYPE NATURAL
set_parameter_property OFFSET_SAIDA UNITS None
set_parameter_property OFFSET_SAIDA ALLOWED_RANGES 0:2147483647
set_parameter_property OFFSET_SAIDA DESCRIPTION ""
set_parameter_property OFFSET_SAIDA HDL_PARAMETER true
add_parameter ESPERANDO STD_LOGIC_VECTOR 1
set_parameter_property ESPERANDO DEFAULT_VALUE 1
set_parameter_property ESPERANDO DISPLAY_NAME ESPERANDO
set_parameter_property ESPERANDO WIDTH 5
set_parameter_property ESPERANDO TYPE STD_LOGIC_VECTOR
set_parameter_property ESPERANDO ENABLED false
set_parameter_property ESPERANDO UNITS None
set_parameter_property ESPERANDO ALLOWED_RANGES 0:31
set_parameter_property ESPERANDO HDL_PARAMETER true
add_parameter CARREGANDO STD_LOGIC_VECTOR 2
set_parameter_property CARREGANDO DEFAULT_VALUE 2
set_parameter_property CARREGANDO DISPLAY_NAME CARREGANDO
set_parameter_property CARREGANDO WIDTH 5
set_parameter_property CARREGANDO TYPE STD_LOGIC_VECTOR
set_parameter_property CARREGANDO ENABLED false
set_parameter_property CARREGANDO UNITS None
set_parameter_property CARREGANDO ALLOWED_RANGES 0:31
set_parameter_property CARREGANDO HDL_PARAMETER true
add_parameter CALCULANDO STD_LOGIC_VECTOR 4
set_parameter_property CALCULANDO DEFAULT_VALUE 4
set_parameter_property CALCULANDO DISPLAY_NAME CALCULANDO
set_parameter_property CALCULANDO WIDTH 5
set_parameter_property CALCULANDO TYPE STD_LOGIC_VECTOR
set_parameter_property CALCULANDO ENABLED false
set_parameter_property CALCULANDO UNITS None
set_parameter_property CALCULANDO ALLOWED_RANGES 0:31
set_parameter_property CALCULANDO HDL_PARAMETER true
add_parameter PRONTO STD_LOGIC_VECTOR 8
set_parameter_property PRONTO DEFAULT_VALUE 8
set_parameter_property PRONTO DISPLAY_NAME PRONTO
set_parameter_property PRONTO WIDTH 5
set_parameter_property PRONTO TYPE STD_LOGIC_VECTOR
set_parameter_property PRONTO ENABLED false
set_parameter_property PRONTO UNITS None
set_parameter_property PRONTO ALLOWED_RANGES 0:31
set_parameter_property PRONTO HDL_PARAMETER true
add_parameter SIZE POSITIVE 128 ""
set_parameter_property SIZE DEFAULT_VALUE 128
set_parameter_property SIZE DISPLAY_NAME SIZE
set_parameter_property SIZE WIDTH ""
set_parameter_property SIZE TYPE POSITIVE
set_parameter_property SIZE UNITS None
set_parameter_property SIZE ALLOWED_RANGES 1:2147483647
set_parameter_property SIZE DESCRIPTION ""
set_parameter_property SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avmclk
# 
add_interface avmclk clock start
set_interface_property avmclk associatedDirectClock ""
set_interface_property avmclk clockRate 0
set_interface_property avmclk clockRateKnown false
set_interface_property avmclk ENABLED true
set_interface_property avmclk EXPORT_OF ""
set_interface_property avmclk PORT_NAME_MAP ""
set_interface_property avmclk CMSIS_SVD_VARIABLES ""
set_interface_property avmclk SVD_ADDRESS_GROUP ""

add_interface_port avmclk cso_avmclk_clk clk Output 1


# 
# connection point avmrst
# 
add_interface avmrst reset start
set_interface_property avmrst associatedClock clock
set_interface_property avmrst associatedDirectReset ""
set_interface_property avmrst associatedResetSinks ""
set_interface_property avmrst synchronousEdges DEASSERT
set_interface_property avmrst ENABLED true
set_interface_property avmrst EXPORT_OF ""
set_interface_property avmrst PORT_NAME_MAP ""
set_interface_property avmrst CMSIS_SVD_VARIABLES ""
set_interface_property avmrst SVD_ADDRESS_GROUP ""

add_interface_port avmrst rso_avmrst_reset reset Output 1


# 
# connection point avalon_master_0
# 
add_interface avalon_master_0 avalon start
set_interface_property avalon_master_0 addressUnits SYMBOLS
set_interface_property avalon_master_0 associatedClock clock
set_interface_property avalon_master_0 associatedReset reset
set_interface_property avalon_master_0 bitsPerSymbol 8
set_interface_property avalon_master_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_0 burstcountUnits WORDS
set_interface_property avalon_master_0 doStreamReads false
set_interface_property avalon_master_0 doStreamWrites false
set_interface_property avalon_master_0 holdTime 0
set_interface_property avalon_master_0 linewrapBursts false
set_interface_property avalon_master_0 maximumPendingReadTransactions 0
set_interface_property avalon_master_0 maximumPendingWriteTransactions 0
set_interface_property avalon_master_0 readLatency 0
set_interface_property avalon_master_0 readWaitTime 1
set_interface_property avalon_master_0 setupTime 0
set_interface_property avalon_master_0 timingUnits Cycles
set_interface_property avalon_master_0 writeWaitTime 0
set_interface_property avalon_master_0 ENABLED true
set_interface_property avalon_master_0 EXPORT_OF ""
set_interface_property avalon_master_0 PORT_NAME_MAP ""
set_interface_property avalon_master_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_0 avm_read read Output 1
add_interface_port avalon_master_0 avm_write write Output 1
add_interface_port avalon_master_0 avm_address address Output 10
add_interface_port avalon_master_0 avm_readdata readdata Input 32
add_interface_port avalon_master_0 avm_writedata writedata Output 32
add_interface_port avalon_master_0 avm_waitrequest waitrequest Input 1
add_interface_port avalon_master_0 avm_byteenable byteenable Output 4


# 
# connection point start
# 
add_interface start conduit end
set_interface_property start associatedClock ""
set_interface_property start associatedReset ""
set_interface_property start ENABLED true
set_interface_property start EXPORT_OF ""
set_interface_property start PORT_NAME_MAP ""
set_interface_property start CMSIS_SVD_VARIABLES ""
set_interface_property start SVD_ADDRESS_GROUP ""

add_interface_port start coe_start_export export Input 1


# 
# connection point finish
# 
add_interface finish conduit end
set_interface_property finish associatedClock ""
set_interface_property finish associatedReset ""
set_interface_property finish ENABLED true
set_interface_property finish EXPORT_OF ""
set_interface_property finish PORT_NAME_MAP ""
set_interface_property finish CMSIS_SVD_VARIABLES ""
set_interface_property finish SVD_ADDRESS_GROUP ""

add_interface_port finish coe_finish_export export Output 1

